
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/a_UAX/PRIMERO/PROGRAMACI\u00d3N/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
